### ISSUE TITLE
to make index.html responsive

### ISSUE THREAD

**Issue by RittikSoni** [RittikSoni/webteam#2]
if you are a beginner, then this is a _good start for you_! **_go ahead_** !! 😀
In this issue, you have to make index.html responsive . . . .

**Comment by prathamesh-borse** [comment]
The index.html Page is already responsive..

**Comment by rtesting** [comment]
> The index.html Page is already responsive.
@viraldevpb
No, it's not responsive, for some devices it's working completely fine but as with the iPad, its hover effect is not responsive.
